### ISSUE TITLE
Change device naming convention

### ISSUE THREAD

**Issue by magik6k** [StarChasers/Plan9k#1]
Switch to using first 3-4 upper characters from device UUID, so that `/dev/sda` becomes `/dev/sdXY1Z` and `/dev/sdb2` becomes `/dev/sdAB3Cp2`
- [x] plan9k-drivers
- [x] plan9k-network

**Comment by Kubuxu** [comment]
Use 3 letters by default and add more in case of collision. Problem that adding device might change name of older device.

**Comment by magik6k** [comment]
This issue was moved to OpenPrograms/Plan9k#1
